### PR TITLE
feat: Add `forEach` method

### LINKED ISSUE #27: Idea: forEach loop
WebTorrent loops over bitfields a bunch of time to check what is done and what not, So I figure this piece could be improved with a smarter forEach loop

```js
  get(i) {
    const j = i >> 3
    return (j < this.buffer.length) &&
      !!(this.buffer[j] & (128 >> (i % 8)))
  }
```
Solution:
```js
  forEach(fn, start = 0, end = this.buffer.length) {
    for (
      let i = start, j = i >> 3, x = i % 8, y = 128 >> x, buffer = this.buffer, byte = buffer[j]; 
      i < end; 
      i++
    ) {
      fn(!!(byte & (y >> x)), i)

      y === 1
        ? (y = y << 7, x = 0, byte = buffer[++j])
        : (y = y >> 1, x++)
    }
  }
```
```
forEach loop: 0.944091796875ms
for loop: 1.72314453125ms
```

fiddle: http://jsfiddle.net/nbr5u3jk/3/

### PR DESCRIPTION
**Pull request by fb55**
Fixes #27

@jimmywarting I know your issue is already two years old. I'd love it if you could have a look!

### CODE REVIEW

**Comment by jimmywarting** [comment]
Hmm, this was 2 years ago... I battle tested my own solution (the one i wrote in the fiddle/issue) in a real application for a while and found something off with it - can't remember what it was - think it was something it did wrong but can't remember what it was. perhaps it was something wrong with starting from a place where it wasn't dividable by 8... can't remember - but i see you wrote a test from `3 to 11` 👍 
unfortunately i didn't write any test on my my parts


but in my fork i ended up with this one:
```js
forEach (fn, start = 0, end = this.buffer.length * 8) {
  for (
    let i = start, j = i >> 3, x = i % 8, y = 128 >> x, buffer = this.buffer, byte = buffer[j];
    i < end;
    i++
  ) {
    fn(!!(byte & (y >> x)), i)

    y = y === 1
      ? (x = 0, byte = buffer[++j], 128)
      : y >> 1
  }
}
```
...and it have worked out well for me for quite a while now without any trouble. 

going back to old source and trying to understand what it dose is hard, especially when it has to do with bits and byte shifting

yours is slightly different in the loop/if statement maybe you did something better.

**Comment by fb55** [comment]
Very interesting, thanks for getting back so quickly! 

There is still an issue in your current solution: You are doing an unnecessary bit shift that misaligns things.

```js
fn(!!(byte & (y >> x)), i)
```

should be

```js
fn(!!(byte & y), i)
```

`x` is the relevant bit inside of the byte and used to calculate `y`, the bit mask to extract the relevant bit. Afterwards, `y` is shifted directly and `x` isn't updated anymore.

This is how you get failing behavior when the start is not a multiple of 8: That is the only case where this shift doesn't do anything.

I've updated this PR to use your solution (with the above fix applied).

**Comment by jimmywarting** [comment]
don't like the typescript part - think it would be fine with just keeping the jsdoc. IDE's can understand them too.
TypeScript adds an overhead to the project, which might not worth it. since typescript don't "actually" run anywhere without being transpiled to js first + you can't import them in the browser

Other than that 👍 
LGTM

**Comment by fb55** [comment]
Thanks for the review! I like the additional layer of safety that TS provides. Not super important for a small library like this, but also it won't hurt 🤷‍♂️

**Comment by jimmywarting** [comment]
>  I like the additional layer of safety that TS provides

You can achieve the same layer of safety with `// @ts-check` and jsdoc?

**Pull request merged**
